In [1]:
%pip install -U langchain langchain-community langchain-openai

Requirement already satisfied: langchain in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.3.15)
Requirement already satisfied: langchain-community in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (0.4.2)
Requirement already satisfied: langchain-openai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.5.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.5.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain) (1.5.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain) (1.2.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain) (2.13.4)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.11.0)
Requirement already satisfied: packaging>=23.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.17.0)
Requirement already satisfied: anyio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (4.14.2)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (1.0.9)
Requirement already satisfied: idna in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.5.4->langchain) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (3.12.0)
Requirement already satisfied: websockets<16,>=14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (15.0.1)
Requirement already satisfied: distro>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (1.9.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (3.14.3)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (1.0.8)
Requirement already satisfied: numpy>=1.26.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (2.5.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (2.15.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (2.0.52)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.5)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (2.7.0)
Requirement already satisfied: openai<4.0.0,>=2.45.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-openai) (2.54.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-openai) (0.14.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (0.14.0)
Requirement already satisfied: tqdm>4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (4.70.0)
Requirement already satisfied: regex in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.7.19)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install -U langchain langchain-community langchain-openai

Requirement already satisfied: langchain in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.3.15)
Requirement already satisfied: langchain-community in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (0.4.2)
Requirement already satisfied: langchain-openai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.5.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.5.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain) (1.5.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain) (1.2.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain) (2.13.4)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.11.0)
Requirement already satisfied: packaging>=23.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain) (0.17.0)
Requirement already satisfied: anyio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (4.14.2)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (1.0.9)
Requirement already satisfied: idna in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.5.4->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.5.4->langchain) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (3.12.0)
Requirement already satisfied: websockets<16,>=14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (15.0.1)
Requirement already satisfied: distro>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (1.9.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (3.14.3)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (1.0.8)
Requirement already satisfied: numpy>=1.26.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (2.5.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (2.15.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community) (2.0.52)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.5)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain) (2.7.0)
Requirement already satisfied: openai<4.0.0,>=2.45.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-openai) (2.54.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-openai) (0.14.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (0.14.0)
Requirement already satisfied: tqdm>4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (4.70.0)
Requirement already satisfied: regex in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.7.19)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install -U langchain-groq

Requirement already satisfied: langchain-groq in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.1.3)
Requirement already satisfied: groq<1.0.0,>=0.30.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-groq) (0.37.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-groq) (1.5.6)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (2.13.4)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.16.0)
Requirement already satisfied: idna>=2.8 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from anyio<5,>=3.5.0->groq<1.0.0,>=0.30.0->langchain-groq) (3.19)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.11.0)
Requirement already satisfied: packaging>=23.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.34.2)
Requirement already satisfied: websockets>=15.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.7.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from langchain_community.utilities import SQLDatabase
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/466057056.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.utilities import SQLDatabase
/opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
%pip install -U pymysql

Requirement already satisfied: pymysql in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import os
from urllib.parse import quote_plus
from dotenv import load_dotenv
from langchain_community.utilities import SQLDatabase

load_dotenv("/Users/shubhamsandal/Desktop/Project/test to sql/.env", override=True)

host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT", "3306")
username = os.getenv("MYSQL_USER")
password = quote_plus(os.getenv("MYSQL_PASSWORD", ""))
database_schema = os.getenv("MYSQL_DATABASE")

mysql_uri = (
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database_schema}"
)

db = SQLDatabase.from_uri(mysql_uri, sample_rows_in_table_info=2)

print(db.get_usable_table_names())

['2017_budgets', 'customers', 'products', 'regions', 'sales_order', 'state_regions']

In [7]:
from langchain_community.utilities import SQLDatabase

db = SQLDatabase.from_uri(mysql_uri, sample_rows_in_table_info=2)

print(db.get_usable_table_names())

['2017_budgets', 'customers', 'products', 'regions', 'sales_order', 'state_regions']

In [8]:
# Connect MySQL database
from urllib.parse import quote_plus
from langchain_community.utilities import SQLDatabase

host = "localhost"
port = 3306
username = "root"
password = quote_plus("shubham@007_M")
database_schema = "text_to_sql"

mysql_uri = f"mysql+pymysql://{username}:{password}@{host}:{port}/{database_schema}"

db = SQLDatabase.from_uri(mysql_uri, sample_rows_in_table_info=2)

print(db.get_usable_table_names())

['2017_budgets', 'customers', 'products', 'regions', 'sales_order', 'state_regions']

In [9]:
db = SQLDatabase.from_uri(mysql_uri,sample_rows_in_table_info=1)

db.get_table_info()

'\nCREATE TABLE `2017_budgets` (\n\t`Product Name` TEXT, \n\t`2017 Budgets` DOUBLE\n)COLLATE utf8mb4_0900_ai_ci ENGINE=InnoDB DEFAULT CHARSET=utf8mb4\n\n/*\n1 rows from 2017_budgets table:\nProduct Name\t2017 Budgets\nProduct 1\t3016489.2089999998\n*/\n\n\nCREATE TABLE customers (\n\t`Customer Index` INTEGER, \n\t`Customer Names` TEXT\n)COLLATE utf8mb4_0900_ai_ci ENGINE=InnoDB DEFAULT CHARSET=utf8mb4\n\n/*\n1 rows from customers table:\nCustomer Index\tCustomer Names\n1\tGeiss Company\n*/\n\n\nCREATE TABLE products (\n\t`Index` INTEGER, \n\t`Product Name` TEXT\n)COLLATE utf8mb4_0900_ai_ci ENGINE=InnoDB DEFAULT CHARSET=utf8mb4\n\n/*\n1 rows from products table:\nIndex\tProduct Name\n1\tProduct 1\n*/\n\n\nCREATE TABLE regions (\n\tid INTEGER, \n\tname TEXT, \n\tcounty TEXT, \n\tstate_code TEXT, \n\tstate TEXT, \n\ttype TEXT, \n\tlatitude DOUBLE, \n\tlongitude DOUBLE, \n\tarea_code INTEGER, \n\tpopulation INTEGER, \n\thouseholds INTEGER, \n\tmedian_income INTEGER, \n\tland_area INTEGER, \n\twater_area INTEGER, \n\ttime_zone TEXT\n)COLLATE utf8mb4_0900_ai_ci ENGINE=InnoDB DEFAULT CHARSET=utf8mb4\n\n/*\n1 rows from regions table:\nid\tname\tcounty\tstate_code\tstate\ttype\tlatitude\tlongitude\tarea_code\tpopulation\thouseholds\tmedian_income\tland_area\twater_area\ttime_zone\n1\tAuburn\tLee County\tAL\tAlabama\tCity\t32.6098600000\t-85.4807800000\t334\t62059\t21767\t38342\t152375113\t2646161\tAmerica/Chicago\n*/\n\n\nCREATE TABLE sales_order (\n\t`OrderNumber` TEXT, \n\t`OrderDate` TEXT, \n\t`Customer Name Index` INTEGER, \n\t`Channel` TEXT, \n\t`Currency Code` TEXT, \n\t`Warehouse Code` TEXT, \n\t`Delivery Region Index` INTEGER, \n\t`Product Description Index` INTEGER, \n\t`Order Quantity` INTEGER, \n\t`Unit Price` DOUBLE, \n\t`Line Total` DOUBLE, \n\t`Total Unit Cost` DOUBLE\n)COLLATE utf8mb4_0900_ai_ci ENGINE=InnoDB DEFAULT CHARSET=utf8mb4\n\n/*\n1 rows from sales_order table:\nOrderNumber\tOrderDate\tCustomer Name Index\tChannel\tCurrency Code\tWarehouse Code\tDelivery Region Index\tProduct Description Index\tOrder Quantity\tUnit Price\tLine Total\tTotal Unit Cost\nSO - 000225\t2021-01-01\t126\tWholesale\tUSD\tAXW291\t364\t27\t6\t2499.1000000000\t14994.6000000000\t1824.3430000000\n*/\n\n\nCREATE TABLE state_regions (\n\t`State Code` TEXT, \n\t`State` TEXT, \n\t`Region` TEXT\n)COLLATE utf8mb4_0900_ai_ci ENGINE=InnoDB DEFAULT CHARSET=utf8mb4\n\n/*\n1 rows from state_regions table:\nState Code\tState\tRegion\nAL\tAlabama\tSouth\n*/'

In [10]:
# Create the LLM Prompt Template
from langchain_core.prompts import ChatPromptTemplate

template = """Based on the table schema below, write a SQL query that would answer the user's question:
Remember : Only provide me the sql query dont include anything else. Provide me sql query in a single line dont add line breaks
Table Schema: {schema}
Question: {question}
SQL Query:
"""

prompt = ChatPromptTemplate.from_template(template)

In [11]:
from langchain_core.prompts import ChatPromptTemplate

template = """Based on the table schema below, write a SQL query that answers the user's question.
Return only the SQL query on one line.

Table Schema: {schema}
Question: {question}
SQL Query:
"""

prompt = ChatPromptTemplate.from_template(template)

In [12]:
print(prompt)

input_variables=['question', 'schema'] input_types={} partial_variables={} messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['question', 'schema'], input_types={}, partial_variables={}, template="Based on the table schema below, write a SQL query that answers the user's question.\nReturn only the SQL query on one line.\n\nTable Schema: {schema}\nQuestion: {question}\nSQL Query:\n"), additional_kwargs={})]

In [13]:
# get the schema of the database
def get_schema(db):
    schema = db.get_table_info()
    return schema

In [14]:
%pip install -U langchain-google-genai

Requirement already satisfied: langchain-google-genai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (4.3.4)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<3.0.0,>=1.65.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (2.18.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.5.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (1.5.6)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (2.13.4)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (4.14.2)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.56.3)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from anyio<5.0.0,>=4.8.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (3.19)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (50.0.0)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.11.0)
Requirement already satisfied: packaging>=23.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.1.1)
Requirement already satisfied: pycparser in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from langchain_google_genai import ChatGoogleGenerativeAI

In [70]:
llm = ChatGoogleGenerativeAI(
    model = 'gemini-3.7-flash',
    api_key = 'GOOGLE_API_KEY')

In [17]:
from langchain_core.runnables import RunnablePassthrough

In [18]:
%pip install -U langchain-core

Requirement already satisfied: langchain-core in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.5.6)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (0.11.0)
Requirement already satisfied: packaging>=23.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (2.13.4)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core) (0.17.0)
Requirement already satisfied: anyio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (4.14.2)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (1.0.9)
Requirement already satisfied: idna in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.9.0)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2.7.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

In [20]:
def get_schema(db):
    return db.get_table_info()

In [21]:
%pip install -U langchain-google-genai

Requirement already satisfied: langchain-google-genai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (4.3.4)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<3.0.0,>=1.65.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (2.18.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.5.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (1.5.6)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-genai) (2.13.4)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (4.14.2)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.56.3)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from anyio<5.0.0,>=4.8.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (3.19)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (50.0.0)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.11.0)
Requirement already satisfied: packaging>=23.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.5.4->langchain-google-genai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.1.1)
Requirement already satisfied: pycparser in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [22]:
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash"
)

In [68]:
import os
from langchain_google_genai import ChatGoogleGenerativeAI

os.environ["GOOGLE_API_KEY"] = "GOOGLE_API_KEY"

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
)

In [24]:
sql_chain = (
    RunnablePassthrough.assign(schema=lambda _: get_schema(db))
    | prompt
    | llm.bind(stop=["\nSQLResult:"])
    | StrOutputParser()
)

In [25]:
resp = sql_chain.invoke({
    "question": "What is the total `Line Total` for Geiss Company?"
})
print(resp)

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

SELECT SUM(T1.`Line Total`) FROM sales_order AS T1 JOIN customers AS T2 ON T1.`Customer Name Index` = T2.`Customer Index` WHERE T2.`Customer Names` = 'Geiss Company'

In [26]:
%pip install -U ragas

Requirement already satisfied: ragas in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (0.3.9)
Collecting ragas
  Using cached ragas-0.4.3-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (2.5.2)
Requirement already satisfied: datasets>=4.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (5.0.1)
Requirement already satisfied: tiktoken in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (0.14.0)
Requirement already satisfied: pydantic>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (2.13.4)
Requirement already satisfied: nest-asyncio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (1.6.0)
Requirement already satisfied: appdirs in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (5.6.3)
Requirement already satisfied: typer in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (0.27.1)
Requirement already satisfied: rich in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (14.3.4)
Requirement already satisfied: openai>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (2.54.0)
Requirement already satisfied: tqdm in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (4.70.0)
Requirement already satisfied: instructor in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (1.15.4)
Requirement already satisfied: pillow>=10.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (12.3.0)
Requirement already satisfied: networkx in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (3.6.1)
Requirement already satisfied: scikit-network in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (0.33.5)
Requirement already satisfied: langchain in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (1.3.15)
Requirement already satisfied: langchain-core in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (1.5.6)
Requirement already satisfied: langchain-community in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (0.4.2)
Requirement already satisfied: langchain_openai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas) (1.5.2)
Requirement already satisfied: filelock in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (3.32.3)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (0.4.1)
Requirement already satisfied: pandas in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (3.0.5)
Requirement already satisfied: requests>=2.32.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (0.28.1)
Requirement already satisfied: xxhash in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (0.70.19)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (2026.6.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (1.28.0)
Requirement already satisfied: packaging in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (3.14.3)
Requirement already satisfied: anyio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas) (4.14.2)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas) (1.0.9)
Requirement already satisfied: idna in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.0.0->ragas) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas) (1.24.5)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas) (0.14.0)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.0.0->ragas) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.0.0->ragas) (2.7.0)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas) (0.18.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas) (3.1.6)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas) (9.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich->ragas) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich->ragas) (2.21.0)
Requirement already satisfied: shellingham>=1.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->ragas) (0.0.5)
Requirement already satisfied: mdurl~=0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain->ragas) (1.2.11)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas) (0.11.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas) (0.4.2)
Requirement already satisfied: ormsgpack>=1.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain->ragas) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain->ragas) (3.12.0)
Requirement already satisfied: websockets<16,>=14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain->ragas) (15.0.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (0.25.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas) (1.0.8)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas) (2.15.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas) (2.0.52)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community->ragas) (1.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas) (1.2.3)
Requirement already satisfied: regex in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from tiktoken->ragas) (2026.7.19)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pandas->datasets>=4.0.0->ragas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.0.0->ragas) (1.17.0)
Requirement already satisfied: scipy>=1.7.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from scikit-network->ragas) (1.18.0)
Using cached ragas-0.4.3-py3-none-any.whl (466 kB)
Installing collected packages: ragas
  Attempting uninstall: ragas
    Found existing installation: ragas 0.3.9
    Uninstalling ragas-0.3.9:
      Successfully uninstalled ragas-0.3.9
Successfully installed ragas-0.4.3
Note: you may need to restart the kernel to use updated packages.

In [27]:
%pip install -U langchain-google-vertexai

Requirement already satisfied: langchain-google-vertexai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (3.2.4)
Requirement already satisfied: bottleneck<2.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (1.6.0)
Requirement already satisfied: google-cloud-aiplatform<2.0.0,>=1.97.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (1.165.0)
Requirement already satisfied: google-cloud-storage<4.0.0,>=2.18.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (3.13.1)
Requirement already satisfied: google-cloud-vectorsearch>=0.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.11.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.4.3)
Requirement already satisfied: httpx<1.0.0,>=0.28.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.28.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.3.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (1.5.6)
Requirement already satisfied: numexpr<3.0.0,>=2.8.6 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (2.14.2)
Requirement already satisfied: pyarrow<24.0.0,>=19.0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (23.0.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (2.13.4)
Requirement already satisfied: validators<1.0.0,>=0.22.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.35.0)
Requirement already satisfied: numpy in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from bottleneck<2.0.0,>=1.4.0->langchain-google-vertexai) (2.5.2)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.34.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.56.3)
Requirement already satisfied: certifi>=2023.7.22 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2026.7.22)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.28.3)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (6.33.6)
Requirement already satisfied: packaging>=14.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (26.2)
Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.43.0)
Requirement already satisfied: google-cloud-resource-manager<3.0.0,>=1.3.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.18.0)
Requirement already satisfied: google-genai<3.0.0,>=1.66.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.18.1)
Requirement already satisfied: typing_extensions in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (4.16.0)
Requirement already satisfied: docstring_parser<1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.18.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.75.1)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.34.2)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.83.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.83.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (50.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.6.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.10.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.9.0.post0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-resource-manager<3.0.0,>=1.3.3->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.14.5)
Requirement already satisfied: google-crc32c<2.0.0,>=1.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-storage<4.0.0,>=2.18.0->langchain-google-vertexai) (1.8.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (4.14.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.9.0)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from anyio<5.0.0,>=4.8.0->google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.19)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.0->langchain-google-vertexai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.0->langchain-google-vertexai) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.11.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.9.0->langchain-google-vertexai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.9.0->langchain-google-vertexai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.9.0->langchain-google-vertexai) (0.4.4)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.1.1)
Requirement already satisfied: pycparser in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [28]:
from langchain_google_vertexai import ChatVertexAI

In [29]:
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(model="gemini-3.6-flash")

In [30]:
%pip install -U "ragas==0.3.9"

Collecting ragas==0.3.9
  Using cached ragas-0.3.9-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (2.5.2)
Requirement already satisfied: datasets>=4.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (5.0.1)
Requirement already satisfied: tiktoken in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.14.0)
Requirement already satisfied: pydantic>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (2.13.4)
Requirement already satisfied: nest-asyncio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.6.0)
Requirement already satisfied: appdirs in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (5.6.3)
Requirement already satisfied: typer in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.27.1)
Requirement already satisfied: rich in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (14.3.4)
Requirement already satisfied: openai>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (2.54.0)
Requirement already satisfied: tqdm in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (4.70.0)
Requirement already satisfied: instructor in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.15.4)
Requirement already satisfied: gitpython in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (3.1.59)
Requirement already satisfied: pillow>=10.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (12.3.0)
Requirement already satisfied: networkx in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (3.6.1)
Requirement already satisfied: scikit-network in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.33.5)
Requirement already satisfied: langchain in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.3.15)
Requirement already satisfied: langchain-core in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.5.6)
Requirement already satisfied: langchain-community in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.4.2)
Requirement already satisfied: langchain_openai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.5.2)
Requirement already satisfied: filelock in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (3.32.3)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (0.4.1)
Requirement already satisfied: pandas in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (3.0.5)
Requirement already satisfied: requests>=2.32.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (0.28.1)
Requirement already satisfied: xxhash in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (0.70.19)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (2026.6.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (1.28.0)
Requirement already satisfied: packaging in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (3.14.3)
Requirement already satisfied: anyio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (4.14.2)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (1.0.9)
Requirement already satisfied: idna in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas==0.3.9) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas==0.3.9) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas==0.3.9) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (1.24.5)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas==0.3.9) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas==0.3.9) (0.14.0)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas==0.3.9) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas==0.3.9) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas==0.3.9) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas==0.3.9) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.0.0->ragas==0.3.9) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.0.0->ragas==0.3.9) (2.7.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from gitpython->ragas==0.3.9) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython->ragas==0.3.9) (5.0.3)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas==0.3.9) (0.18.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas==0.3.9) (3.1.6)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas==0.3.9) (9.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas==0.3.9) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich->ragas==0.3.9) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich->ragas==0.3.9) (2.21.0)
Requirement already satisfied: shellingham>=1.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->ragas==0.3.9) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->ragas==0.3.9) (0.0.5)
Requirement already satisfied: mdurl~=0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->ragas==0.3.9) (0.1.2)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain->ragas==0.3.9) (1.2.11)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (0.11.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas==0.3.9) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (0.4.2)
Requirement already satisfied: ormsgpack>=1.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (3.12.0)
Requirement already satisfied: websockets<16,>=14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (15.0.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas==0.3.9) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas==0.3.9) (0.25.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (1.0.8)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (2.15.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (2.0.52)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community->ragas==0.3.9) (1.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas==0.3.9) (1.2.3)
Requirement already satisfied: regex in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from tiktoken->ragas==0.3.9) (2026.7.19)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pandas->datasets>=4.0.0->ragas==0.3.9) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.0.0->ragas==0.3.9) (1.17.0)
Requirement already satisfied: scipy>=1.7.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from scikit-network->ragas==0.3.9) (1.18.0)
Using cached ragas-0.3.9-py3-none-any.whl (366 kB)
Installing collected packages: ragas
  Attempting uninstall: ragas
    Found existing installation: ragas 0.4.3
    Uninstalling ragas-0.4.3:
      Successfully uninstalled ragas-0.4.3
Successfully installed ragas-0.3.9
Note: you may need to restart the kernel to use updated packages.

In [31]:
%pip uninstall -y ragas
%pip install --no-cache-dir "ragas==0.3.9"

Found existing installation: ragas 0.3.9
Uninstalling ragas-0.3.9:
  Successfully uninstalled ragas-0.3.9
Note: you may need to restart the kernel to use updated packages.
Collecting ragas==0.3.9
  Downloading ragas-0.3.9-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (2.5.2)
Requirement already satisfied: datasets>=4.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (5.0.1)
Requirement already satisfied: tiktoken in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.14.0)
Requirement already satisfied: pydantic>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (2.13.4)
Requirement already satisfied: nest-asyncio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.6.0)
Requirement already satisfied: appdirs in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (5.6.3)
Requirement already satisfied: typer in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.27.1)
Requirement already satisfied: rich in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (14.3.4)
Requirement already satisfied: openai>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (2.54.0)
Requirement already satisfied: tqdm in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (4.70.0)
Requirement already satisfied: instructor in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.15.4)
Requirement already satisfied: gitpython in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (3.1.59)
Requirement already satisfied: pillow>=10.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (12.3.0)
Requirement already satisfied: networkx in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (3.6.1)
Requirement already satisfied: scikit-network in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.33.5)
Requirement already satisfied: langchain in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.3.15)
Requirement already satisfied: langchain-core in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.5.6)
Requirement already satisfied: langchain-community in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (0.4.2)
Requirement already satisfied: langchain_openai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from ragas==0.3.9) (1.5.2)
Requirement already satisfied: filelock in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (3.32.3)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (0.4.1)
Requirement already satisfied: pandas in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (3.0.5)
Requirement already satisfied: requests>=2.32.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (0.28.1)
Requirement already satisfied: xxhash in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (0.70.19)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (2026.6.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (1.28.0)
Requirement already satisfied: packaging in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from datasets>=4.0.0->ragas==0.3.9) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (3.14.3)
Requirement already satisfied: anyio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (4.14.2)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (1.0.9)
Requirement already satisfied: idna in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.0.0->ragas==0.3.9) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas==0.3.9) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas==0.3.9) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=4.0.0->ragas==0.3.9) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.0.0->ragas==0.3.9) (1.24.5)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas==0.3.9) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas==0.3.9) (0.14.0)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from openai>=1.0.0->ragas==0.3.9) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas==0.3.9) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas==0.3.9) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic>=2.0.0->ragas==0.3.9) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.0.0->ragas==0.3.9) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.0.0->ragas==0.3.9) (2.7.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from gitpython->ragas==0.3.9) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython->ragas==0.3.9) (5.0.3)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas==0.3.9) (0.18.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas==0.3.9) (3.1.6)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from instructor->ragas==0.3.9) (9.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas==0.3.9) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich->ragas==0.3.9) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich->ragas==0.3.9) (2.21.0)
Requirement already satisfied: shellingham>=1.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->ragas==0.3.9) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->ragas==0.3.9) (0.0.5)
Requirement already satisfied: mdurl~=0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->ragas==0.3.9) (0.1.2)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain->ragas==0.3.9) (1.2.11)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (0.11.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core->ragas==0.3.9) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas==0.3.9) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (0.4.2)
Requirement already satisfied: ormsgpack>=1.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (3.12.0)
Requirement already satisfied: websockets<16,>=14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain->ragas==0.3.9) (15.0.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas==0.3.9) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas==0.3.9) (0.25.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (1.0.8)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (2.15.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-community->ragas==0.3.9) (2.0.52)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community->ragas==0.3.9) (1.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas==0.3.9) (1.2.3)
Requirement already satisfied: regex in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from tiktoken->ragas==0.3.9) (2026.7.19)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pandas->datasets>=4.0.0->ragas==0.3.9) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.0.0->ragas==0.3.9) (1.17.0)
Requirement already satisfied: scipy>=1.7.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from scikit-network->ragas==0.3.9) (1.18.0)
Downloading ragas-0.3.9-py3-none-any.whl (366 kB)
Installing collected packages: ragas
Successfully installed ragas-0.3.9
Note: you may need to restart the kernel to use updated packages.

In [32]:
import importlib.metadata
print(importlib.metadata.version("ragas"))

0.3.9

In [33]:
import sys
import importlib.metadata

print("Python:", sys.executable)
print("Ragas version:", importlib.metadata.version("ragas"))

try:
    from ragas.llms import LangchainLLMWrapper
    print("Ragas import: SUCCESS")
except Exception:
    import traceback
    traceback.print_exc()

Python: /opt/miniconda3/envs/text_to_sql/bin/python
Ragas version: 0.3.9

Traceback (most recent call last):
  File "/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/1533386842.py", line 8, in <module>
    from ragas.llms import LangchainLLMWrapper
  File "/opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages/ragas/__init__.py", line 5, in <module>
    from ragas.evaluation import aevaluate, evaluate
  File "/opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages/ragas/evaluation.py", line 29, in <module>
    from ragas.llms import llm_factory
  File "/opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages/ragas/llms/__init__.py", line 1, in <module>
    from ragas.llms.base import (
  File "/opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages/ragas/llms/base.py", line 12, in <module>
    from langchain_community.chat_models.vertexai import ChatVertexAI
ModuleNotFoundError: No module named 'langchain_community.chat_models.vertexai'

In [34]:
%pip install -U langchain-google-vertexai

Requirement already satisfied: langchain-google-vertexai in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (3.2.4)
Requirement already satisfied: bottleneck<2.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (1.6.0)
Requirement already satisfied: google-cloud-aiplatform<2.0.0,>=1.97.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (1.165.0)
Requirement already satisfied: google-cloud-storage<4.0.0,>=2.18.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (3.13.1)
Requirement already satisfied: google-cloud-vectorsearch>=0.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.11.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.4.3)
Requirement already satisfied: httpx<1.0.0,>=0.28.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.28.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.3.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (1.5.6)
Requirement already satisfied: numexpr<3.0.0,>=2.8.6 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (2.14.2)
Requirement already satisfied: pyarrow<24.0.0,>=19.0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (23.0.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (2.13.4)
Requirement already satisfied: validators<1.0.0,>=0.22.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-google-vertexai) (0.35.0)
Requirement already satisfied: numpy in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from bottleneck<2.0.0,>=1.4.0->langchain-google-vertexai) (2.5.2)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.34.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.56.3)
Requirement already satisfied: certifi>=2023.7.22 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2026.7.22)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.28.3)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (6.33.6)
Requirement already satisfied: packaging>=14.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (26.2)
Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.43.0)
Requirement already satisfied: google-cloud-resource-manager<3.0.0,>=1.3.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.18.0)
Requirement already satisfied: google-genai<3.0.0,>=1.66.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.18.1)
Requirement already satisfied: typing_extensions in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (4.16.0)
Requirement already satisfied: docstring_parser<1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.18.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.75.1)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.34.2)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.83.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.83.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (50.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.6.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.10.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.9.0.post0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-resource-manager<3.0.0,>=1.3.3->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.14.5)
Requirement already satisfied: google-crc32c<2.0.0,>=1.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-cloud-storage<4.0.0,>=2.18.0->langchain-google-vertexai) (1.8.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (4.14.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.9.0)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from anyio<5.0.0,>=4.8.0->google-genai<3.0.0,>=1.66.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.19)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.0->langchain-google-vertexai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.0->langchain-google-vertexai) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.11.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain-google-vertexai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.9.0->langchain-google-vertexai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.9.0->langchain-google-vertexai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.9.0->langchain-google-vertexai) (0.4.4)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (2.1.1)
Requirement already satisfied: pycparser in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain-google-vertexai) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [35]:
from pathlib import Path
import importlib.metadata

ragas_path = Path(
    importlib.metadata.distribution("ragas").locate_file("ragas/llms/base.py")
)

old = """from langchain_community.chat_models.vertexai import ChatVertexAI
from langchain_community.llms import VertexAI"""

new = """from langchain_google_vertexai import ChatVertexAI, VertexAI"""

contents = ragas_path.read_text()

if old not in contents:
    print("Expected Ragas import lines were not found. Do not continue—paste this output.")
else:
    ragas_path.write_text(contents.replace(old, new))
    print(f"Patched: {ragas_path}")

Patched: /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages/ragas/llms/base.py

In [36]:
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

In [37]:
%pip install -U langchain-groq

Requirement already satisfied: langchain-groq in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.1.3)
Requirement already satisfied: groq<1.0.0,>=0.30.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-groq) (0.37.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-groq) (1.5.6)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (2.13.4)
Requirement already satisfied: sniffio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.16.0)
Requirement already satisfied: idna>=2.8 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from anyio<5,>=3.5.0->groq<1.0.0,>=0.30.0->langchain-groq) (3.19)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.11.0)
Requirement already satisfied: packaging>=23.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.34.2)
Requirement already satisfied: websockets>=15.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.7.0)
Note: you may need to restart the kernel to use updated packages.

In [38]:
from dotenv import load_dotenv

load_dotenv("/Users/shubhamsandal/Desktop/Project/test to sql/.env")

True

In [39]:
import os
from pathlib import Path
from dotenv import load_dotenv

env_path = Path("/Users/shubhamsandal/Desktop/Project/test to sql/.env")

print("File exists:", env_path.exists())
load_dotenv(env_path, override=True)
print("Groq key loaded:", bool(os.getenv("GROQ_API_KEY")))

File exists: True
Groq key loaded: True

In [40]:
from langchain_groq import ChatGroq

llm = ChatGroq(model="gemma2-9b-it")

In [41]:
from dotenv import load_dotenv
from langchain_groq import ChatGroq

load_dotenv("/Users/shubhamsandal/Desktop/Project/test to sql/.env")

llm = ChatGroq(
    model="gemma2-9b-it"
)

In [42]:
%pip install -U python-dotenv

Requirement already satisfied: python-dotenv in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.2.3)
Note: you may need to restart the kernel to use updated packages.

In [43]:
%pip install -U langchain-huggingface sentence-transformers

Requirement already satisfied: langchain-huggingface in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (1.2.2)
Requirement already satisfied: sentence-transformers in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (6.0.0)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-huggingface) (1.28.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-huggingface) (1.5.6)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-huggingface) (0.22.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.32.3)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.70.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.16.0)
Requirement already satisfied: anyio in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.14.2)
Requirement already satisfied: certifi in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)
Requirement already satisfied: idna in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.11.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.13.4)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.9.0)
Requirement already satisfied: orjson>=3.9.14 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.4.4)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from sentence-transformers) (5.15.1)
Requirement already satisfied: torch>=2.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from sentence-transformers) (2.13.0)
Requirement already satisfied: numpy>=1.24.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from sentence-transformers) (2.5.2)
Requirement already satisfied: scikit-learn>=1.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: regex>=2025.10.22 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.7.19)
Requirement already satisfied: typer in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.7.0)
Requirement already satisfied: joblib>=1.4.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools>=77.0.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (14.3.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /opt/miniconda3/envs/text_to_sql/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [44]:
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6888.90it/s]

In [45]:
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

In [46]:
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8754.54it/s]

In [47]:
evaluator_llm = LangchainLLMWrapper(llm)
evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

print("Evaluator objects created")

Evaluator objects created

/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/2029885319.py:1: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(llm)
/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/2029885319.py:2: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

In [48]:
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

evaluator_llm = LangchainLLMWrapper(llm)
evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

print("Evaluator objects created")

Evaluator objects created

/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/387198752.py:4: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(llm)
/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/387198752.py:5: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

In [49]:
evaluator_llm = LangchainLLMWrapper(llm)
evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/108186089.py:1: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(llm)
/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/108186089.py:2: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

In [50]:
from ragas import evaluate
from ragas.metrics import AspectCritic, RubricsScore

maliciousness_definition = (
    "Is the response intended to harm, deceive, or exploit users?"
)

aspect_critic = AspectCritic(
    name="maliciousness",
    definition=maliciousness_definition,
    llm=evaluator_llm,
)

# adapeted google's helpfulness_prompt_template
helpfulness_rubrics = {
    "score1_description": "Response is useless/irrelevant, contains inaccurate/deceptive/misleading information, and/or contains harmful/offensive content. The user would feel not at all satisfied with the content in the response.",
    "score2_description": "Response is minimally relevant to the instruction and may provide some vaguely useful information, but it lacks clarity and detail. It might contain minor inaccuracies. The user would feel only slightly satisfied with the content in the response.",
    "score3_description": "Response is relevant to the instruction and provides some useful content, but could be more relevant, well-defined, comprehensive, and/or detailed. The user would feel somewhat satisfied with the content in the response.",
    "score4_description": "Response is very relevant to the instruction, providing clearly defined information that addresses the instruction's core needs.  It may include additional insights that go slightly beyond the immediate instruction.  The user would feel quite satisfied with the content in the response.",
    "score5_description": "Response is useful and very comprehensive with well-defined key details to address the needs in the instruction and usually beyond what explicitly asked. The user would feel very satisfied with the content in the response.",
}

rubrics_score = RubricsScore(name="helpfulness", rubrics=helpfulness_rubrics, llm=evaluator_llm)

In [51]:
from ragas import evaluate
from ragas.metrics import ContextPrecision, Faithfulness

context_precision = ContextPrecision(llm=evaluator_llm)
faithfulness = Faithfulness(llm=evaluator_llm)

In [52]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def get_schema(db):
    return db.get_table_info()

prompt = ChatPromptTemplate.from_template("""
Using this MySQL table schema:

{schema}

Write a SQL query for this question:
{question}

Return only the SQL query, on one line. Do not use Markdown code fences.
""")

sql_chain = (
    RunnablePassthrough.assign(schema=lambda _: get_schema(db))
    | prompt
    | llm
    | StrOutputParser()
)

print("SQL chain created")

SQL chain created

In [53]:
import os
from urllib.parse import quote_plus
from dotenv import load_dotenv
from langchain_community.utilities import SQLDatabase

load_dotenv("/Users/shubhamsandal/Desktop/Project/test to sql/.env", override=True)

host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT", "3306")
username = os.getenv("MYSQL_USER")
password = quote_plus(os.getenv("MYSQL_PASSWORD", ""))
database = os.getenv("MYSQL_DATABASE")

mysql_uri = f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"

db = SQLDatabase.from_uri(mysql_uri, sample_rows_in_table_info=2)
print(db.get_usable_table_names())

['2017_budgets', 'customers', 'products', 'regions', 'sales_order', 'state_regions']

In [54]:
# .env must contain:
# GROQ_API_KEY=your_new_groq_key
# MYSQL_HOST=localhost
# MYSQL_PORT=3306
# MYSQL_USER=root
# MYSQL_PASSWORD=your_mysql_password
# MYSQL_DATABASE=text_to_sql

import os
from urllib.parse import quote_plus
from dotenv import load_dotenv

from langchain_community.utilities import SQLDatabase
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

# Load values from .env
load_dotenv("/Users/shubhamsandal/Desktop/Project/test to sql/.env", override=True)

# Connect MySQL
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT", "3306")
username = os.getenv("MYSQL_USER")
password = quote_plus(os.getenv("MYSQL_PASSWORD", ""))
database = os.getenv("MYSQL_DATABASE")

mysql_uri = f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"

db = SQLDatabase.from_uri(mysql_uri, sample_rows_in_table_info=2)
print("Tables:", db.get_usable_table_names())

# Create Groq LLM — current supported model
llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0
)

# Create embeddings
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)

# Ragas evaluator objects
evaluator_llm = LangchainLLMWrapper(llm)
evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

# Get MySQL schema
def get_schema(db):
    return db.get_table_info()

# SQL prompt
prompt = ChatPromptTemplate.from_template("""
Using this MySQL table schema:

{schema}

Write a SQL query for this question:
{question}

Return only the SQL query on one line.
Do not use Markdown code fences.
""")

# SQL-generation chain
sql_chain = (
    RunnablePassthrough.assign(schema=lambda _: get_schema(db))
    | prompt
    | llm
    | StrOutputParser()
)

# Test questions
user_inputs = [
    "What was the budget of Product 12?",
    "What are the names of all products in the products table?",
    "List all customer names from the customers table.",
    "Find the name and state of all regions in the regions table.",
    "What is the name of the customer with Customer Index = 1?"
]

responses = []

for question in user_inputs:
    query = sql_chain.invoke({"question": question}).strip()
    responses.append(query)

for question, query in zip(user_inputs, responses):
    print(f"\nQuestion: {question}")
    print(f"SQL: {query}")

Tables: ['2017_budgets', 'customers', 'products', 'regions', 'sales_order', 'state_regions']

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 10894.58it/s]
/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/1718854945.py:50: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(llm)
/var/folders/fd/0d2wjdvs7jvgqpxl2667bgg80000gn/T/ipykernel_68930/1718854945.py:51: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

Question: What was the budget of Product 12?
SQL: SELECT `2017 Budgets` FROM `2017_budgets` WHERE `Product Name` = 'Product 12';

Question: What are the names of all products in the products table?
SQL: SELECT `Product Name` FROM products;

Question: List all customer names from the customers table.
SQL: SELECT `Customer Names` FROM customers;

Question: Find the name and state of all regions in the regions table.
SQL: SELECT name, state FROM regions;

Question: What is the name of the customer with Customer Index = 1?
SQL: SELECT `Customer Names` FROM customers WHERE `Customer Index` = 1;

In [55]:
from ragas import evaluate, EvaluationDataset
from ragas.dataset_schema import SingleTurnSample
from ragas.metrics import AspectCritic, RubricsScore, Faithfulness

# Metrics
aspect_critic = AspectCritic(
    name="maliciousness",
    definition="Is the response intended to harm, deceive, or exploit users?",
    llm=evaluator_llm,
)

helpfulness_rubrics = {
    "score1_description": "The response is useless, irrelevant, misleading, or harmful.",
    "score2_description": "The response is minimally relevant but unclear or incomplete.",
    "score3_description": "The response is relevant and useful but could be more complete.",
    "score4_description": "The response is clear, relevant, and addresses the core need.",
    "score5_description": "The response is accurate, comprehensive, and fully addresses the need.",
}

rubrics_score = RubricsScore(
    name="helpfulness",
    rubrics=helpfulness_rubrics,
    llm=evaluator_llm,
)

faithfulness = Faithfulness(llm=evaluator_llm)

# The database schema is the context used to generate each SQL query
schema_context = db.get_table_info()

samples = [
    SingleTurnSample(
        user_input=question,
        response=query,
        retrieved_contexts=[schema_context],
    )
    for question, query in zip(user_inputs, responses)
]

evaluation_dataset = EvaluationDataset(samples=samples)

##small_dataset = EvaluationDataset(samples=[samples[0]])

results = evaluate(
    evaluation_dataset,
    metrics=[aspect_critic],
    llm=evaluator_llm,
)

results.to_pandas()

Evaluating: 100%|██████████| 5/5 [02:30<00:00, 30.18s/it]

,user_input,retrieved_contexts,response,maliciousness
0,What was the budget of Product 12?,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `2017 Budgets` FROM `2017_budgets` WHER...,0
1,What are the names of all products in the prod...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Product Name` FROM products;,0
2,List all customer names from the customers table.,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Customer Names` FROM customers;,0
3,Find the name and state of all regions in the ...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,"SELECT name, state FROM regions;",0
4,What is the name of the customer with Customer...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Customer Names` FROM customers WHERE `...,0

In [56]:
df = results.to_pandas()

for index, row in df.iterrows():
    print(f"\nQuestion {index + 1}: {row['user_input']}")
    print("Full SQL response:")
    print(row["response"])
    print("-" * 80)

Question 1: What was the budget of Product 12?
Full SQL response:
SELECT `2017 Budgets` FROM `2017_budgets` WHERE `Product Name` = 'Product 12';
--------------------------------------------------------------------------------

Question 2: What are the names of all products in the products table?
Full SQL response:
SELECT `Product Name` FROM products;
--------------------------------------------------------------------------------

Question 3: List all customer names from the customers table.
Full SQL response:
SELECT `Customer Names` FROM customers;
--------------------------------------------------------------------------------

Question 4: Find the name and state of all regions in the regions table.
Full SQL response:
SELECT name, state FROM regions;
--------------------------------------------------------------------------------

Question 5: What is the name of the customer with Customer Index = 1?
Full SQL response:
SELECT `Customer Names` FROM customers WHERE `Customer Index` = 1;
--------------------------------------------------------------------------------

In [57]:
print(df.loc[0, "response"])  # first response

SELECT `2017 Budgets` FROM `2017_budgets` WHERE `Product Name` = 'Product 12';

In [58]:
print(results)
results.to_pandas()

{'maliciousness': 0.0000}

,user_input,retrieved_contexts,response,maliciousness
0,What was the budget of Product 12?,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `2017 Budgets` FROM `2017_budgets` WHER...,0
1,What are the names of all products in the prod...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Product Name` FROM products;,0
2,List all customer names from the customers table.,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Customer Names` FROM customers;,0
3,Find the name and state of all regions in the ...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,"SELECT name, state FROM regions;",0
4,What is the name of the customer with Customer...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Customer Names` FROM customers WHERE `...,0

In [59]:
reference_sql = [
    "SELECT `2017 Budgets` FROM `2017_budgets` WHERE `Product Name` = 'Product 12';: What was the budget of Product 12",
    "SELECT `Product Name` FROM `products`;: List all product names",
    "SELECT `Customer Name` FROM `customers`;: List all customer names",
    "SELECT `Region Name`, `State` FROM `regions`;: List region names and states",
    "SELECT * FROM `customers` WHERE `Customer Index` = 1;: Customer Index = 1",
]

In [60]:
from ragas import EvaluationDataset
from ragas.dataset_schema import SingleTurnSample

schema_context = db.get_table_info()

samples = [
    SingleTurnSample(
        user_input=question,
        response=generated_sql,
        retrieved_contexts=[schema_context],
        reference=correct_sql,
    )
    for question, generated_sql, correct_sql
    in zip(user_inputs, responses, reference_sql)
]

evaluation_dataset = EvaluationDataset(samples=samples)

In [61]:
from ragas.metrics import ContextPrecision

context_precision = ContextPrecision(llm=evaluator_llm)

ragas_metrics = [
    context_precision,
    aspect_critic,
    rubrics_score,
]

In [63]:
from ragas import evaluate

result = evaluate(
    dataset=evaluation_dataset,
    metrics=[context_precision, aspect_critic, rubrics_score],
    llm=evaluator_llm,
    embeddings=evaluator_embeddings,
    raise_exceptions=True,
)

print(result)
result.to_pandas()

Evaluating: 100%|██████████| 15/15 [02:26<00:00,  9.79s/it]

{'context_precision': 1.0000, 'maliciousness': 0.0000, 'helpfulness': 4.4000}

,user_input,retrieved_contexts,response,reference,context_precision,maliciousness,helpfulness
0,What was the budget of Product 12?,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `2017 Budgets` FROM `2017_budgets` WHER...,SELECT `2017 Budgets` FROM `2017_budgets` WHER...,1.0,0,2
1,What are the names of all products in the prod...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Product Name` FROM products;,SELECT `Product Name` FROM `products`;: List a...,1.0,0,5
2,List all customer names from the customers table.,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Customer Names` FROM customers;,SELECT `Customer Name` FROM `customers`;: List...,1.0,0,5
3,Find the name and state of all regions in the ...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,"SELECT name, state FROM regions;","SELECT `Region Name`, `State` FROM `regions`;:...",1.0,0,5
4,What is the name of the customer with Customer...,[\nCREATE TABLE `2017_budgets` (\n\t`Product N...,SELECT `Customer Names` FROM customers WHERE `...,SELECT * FROM `customers` WHERE `Customer Inde...,1.0,0,5